### PR TITLE
Check season intervals

### LINKED ISSUE #20: `is_valid` errors on an interval with a season
Example is `is_valid('2012/2019-22')` due to [`to_date = datetime.datetime.strptime(parts[1], "%Y-%m")`] not being able to parse a season (i.e. 21, 22, 23, or 24) in the month place. Though it is not completely clear to some of us in the draft specification we are following if a season in the interval should be valid, I think @htarver wants this to be valid assuming the interval makes sense as far as the end date coming after the start date. Valid or not, we should avoid the exception.

### PR DESCRIPTION
**Pull request by ldko**
Currently an exception is thrown when trying to validate a date like `1952-23/1952` or `1952/1953-22` because when checking if the interval is valid, `datetime.datetime.strptime` tries to parse a month and throws an exception because it doesn't handle the numbers we are using for seasons. 

The validity of season intervals seems to be intentionally left out of the draft or formal edtf specification, so I asked @htarver what she deemed to be appropriate for validating them. That is where the from/to ranges come from in the code addition.

This should fix #20 . Ping @madhulika95b @somexpert

### CODE REVIEW

**Comment by htarver** [comment]
That doesn't seem right.  Should it not just check that the season number in the right half is larger than the one in the left half?  Is that how month validation works?

**Comment by somexpert** [comment]
Well since there's no guarantee that _both_ sides will be a season, the code is assigning the earliest/latest month (depending on which side of the range it's on) of the season and then doing the comparison

**Comment by htarver** [comment]
Ok -- I'm seeing the notes, too.  I know Lauren and I talked about the ranges, which do currently overlap a little.  There's no good way to do that.  I think it will be fine for now and should come up too often, anyhow.

**Comment by ldko** [comment]
I could put in an extra check for the case that @somexpert  pointed out that happens when the month ranges overlap and the year is the same.

**Comment by somexpert** [comment]
I already approved this, but now it's _extra_ approved :thumbsup:

**Comment by htarver** [comment]
Thank you :)

**Comment by madhulika95b** [comment]
:+1:  The change log looks good!

**Comment by somexpert** [comment]
_triple_ approved! :thumbsup:

**Pull request merged**
